import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import jwt from 'jsonwebtoken';
import {createApp} from '../app.js';
import {createMemoryStore} from '../repositories/memoryStore.js';
import {hashPassword} from '../utils/password.js';
const passwordHash=await hashPassword('AdminTest123!');
async function fixture(t,extra={}){
 const store=createMemoryStore();const admin=store.create('users',{name:'Administrator',email:'admin@test.com',role:'admin',passwordHash});let now=new Date();
 const settings={jwtSecret:'test-only-signing-key-longer-than-32-characters',sessionSeconds:3600,authLimit:100,...extra};
 const server=createApp({store,settings,clock:()=>now}).listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise(resolve=>{server.close(resolve);server.closeAllConnections();}));
 const base=`http://127.0.0.1:${server.address().port}/api`;
 const client=()=>{let cookie='';return {cookie:()=>cookie,setCookie:value=>{cookie=value;},async request(path,method='GET',body,headers={}){const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json','X-Requested-With':'Gather',Cookie:cookie,...headers},body:body===undefined?undefined:JSON.stringify(body)});const setCookie=res.headers.get('set-cookie');if(setCookie)cookie=setCookie.split(';')[0];return {status:res.status,body:res.status===204?null:await res.json(),cookie:setCookie};}};};
 return {store,admin,client,settings,advance:ms=>{now=new Date(now.getTime()+ms);}};
}
const signup=(client,email='user@test.com')=>client.request('/auth/register','POST',{name:'Test User',email,password:'Password123!'});
const signin=client=>client.request('/auth/login','POST',{email:'admin@test.com',password:'AdminTest123!'});

test('unauthenticated URLs and APIs cannot read or write records',async t=>{const {client}=await fixture(t);const c=client();for(const path of ['/restaurants','/tables','/reservations','/users','/auth/me'])assert.equal((await c.request(path)).status,401,path);assert.equal((await c.request('/restaurants','POST',{name:'No',address:'No'})).status,401);assert.equal((await c.request('/auth/register','POST',{name:'Evil',email:'evil@test.com',password:'Password123!',role:'admin'})).status,400);});

test('real password login, cookie flags, tamper rejection, logout revocation and expiry',async t=>{const f=await fixture(t);const c=f.client();const registered=await signup(c);assert.equal(registered.status,201);assert.equal(registered.body.data.role,'user');assert.ok(!('passwordHash' in registered.body.data));assert.match(registered.cookie,/HttpOnly/i);assert.match(registered.cookie,/SameSite=Lax/i);assert.ok((await f.store.list('users')).find(u=>u.id===registered.body.data.id).passwordHash!=='Password123!');const old=c.cookie();assert.equal((await c.request('/auth/me')).status,200);assert.equal((await c.request('/auth/logout')).status,404);assert.equal((await c.request('/auth/me')).status,200,'GET logout does not log out');await c.request('/auth/logout','POST');c.setCookie(old);assert.equal((await c.request('/auth/me')).status,401);assert.equal((await c.request('/auth/login','POST',{email:'user@test.com',password:'wrongpassword'})).status,401);await c.request('/auth/login','POST',{email:'user@test.com',password:'Password123!'});const current=c.cookie();c.setCookie(current+'tamper');assert.equal((await c.request('/auth/me')).status,401);c.setCookie(current);f.advance(3601000);assert.equal((await c.request('/auth/me')).status,401);});

test('CSRF checks reject missing custom headers and foreign origins',async t=>{const {client}=await fixture(t);const c=client();const body={name:'X',email:'x@test.com',password:'Password123!'};assert.equal((await c.request('/auth/register','POST',body,{'X-Requested-With':''})).status,403);assert.equal((await c.request('/auth/register','POST',body,{Origin:'https://attacker.example'})).status,403);assert.equal((await c.request('/auth/register','POST',body,{Origin:'http://localhost:5173'})).status,201);});

test('roles and ownership enforced on read, update, delete, list and availability exclusion',async t=>{const {client}=await fixture(t);const a=client(),u=client(),other=client();await signin(a);await signup(u);await signup(other,'other@test.com');const venue=(await a.request('/restaurants','POST',{name:'Test Kitchen',address:'Manila'})).body.data;const table=(await a.request('/tables','POST',{restaurantId:venue.id,label:'T1',capacity:4})).body.data;assert.equal((await u.request('/users')).status,403);assert.equal((await u.request('/restaurants','POST',{name:'Denied',address:'Denied'})).status,403);const body={tableId:table.id,guestCount:2,startAt:new Date(Date.now()+86400000).toISOString(),durationMinutes:60};const booking=(await u.request('/reservations','POST',body)).body.data;assert.ok(booking);assert.equal((await other.request('/reservations')).body.data.length,0);for(const method of ['GET','PUT','DELETE'])assert.equal((await other.request(`/reservations/${booking.id}`,method,method==='PUT'?{notes:'stolen'}:undefined)).status,404);assert.equal((await other.request(`/availability?restaurantId=${venue.id}&startAt=${body.startAt}&excludeId=${booking.id}`)).status,404);assert.equal((await u.request(`/reservations/${booking.id}`,'PUT',{userId:'forged'})).status,400);assert.equal((await u.request(`/reservations/${booking.id}`,'PUT',{notes:'Updated'})).status,200);assert.equal((await u.request(`/reservations/${booking.id}`,'PATCH',{status:'completed'})).status,403);assert.equal((await u.request(`/reservations/${booking.id}`,'DELETE')).status,204);});

test('profile changes require current password, revoke old sessions, preserve ownership and cannot change role',async t=>{const {client}=await fixture(t);const u=client(),second=client();const created=await signup(u);await second.request('/auth/login','POST',{email:'user@test.com',password:'Password123!'});assert.equal((await u.request('/auth/profile','PUT',{role:'admin'})).status,400);assert.equal((await u.request('/auth/profile','PUT',{email:'new@test.com'})).status,400);const result=await u.request('/auth/profile','PUT',{name:'Updated',email:'new@test.com',password:'Changed123!',currentPassword:'Password123!'});assert.equal(result.status,200);assert.equal(result.body.data.id,created.body.data.id);assert.equal((await u.request('/auth/me')).status,200);assert.equal((await second.request('/auth/me')).status,401);});

test('admin role/password changes and deletion revoke sessions',async t=>{const {client}=await fixture(t);const a=client(),u=client();await signin(a);const user=(await signup(u)).body.data;assert.equal((await a.request(`/users/${user.id}`,'PUT',{role:'admin'})).status,200);assert.equal((await u.request('/users')).status,401);await u.request('/auth/login','POST',{email:user.email,password:'Password123!'});assert.equal((await u.request('/users')).status,200);assert.equal((await a.request(`/users/${user.id}`,'DELETE')).status,204);assert.equal((await u.request('/auth/me')).status,401);});

test('validly signed JWT without a registered session is rejected and login is rate limited',async t=>{const f=await fixture(t,{authLimit:2});const c=f.client();const token=jwt.sign({sid:'nonexistent'},f.settings.jwtSecret,{algorithm:'HS256',subject:f.admin.id,issuer:'gather',audience:'gather-web',expiresIn:3600});c.setCookie('gather_session='+token);assert.equal((await c.request('/users')).status,401);await signin(c);await signin(c);assert.equal((await signin(c)).status,429);});
